services:
  unifi-timelapser:
    build: .
    container_name: unifi-timelapser
    image: unifi-timelapser:latest
    volumes:
      - ./unifi-timelapser/media:/media
      - ./unifi-timelapser/logs:/logs
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      CAMERA_RTSPS_LIST: ${CAMERA_RTSPS_LIST}
      CAMERA_NAME_LIST: ${CAMERA_NAME_LIST}
      ROTATION_LIST: right,right  # Options: none, left, right, invert
      OUTPUT_DIR: /media
      IMAGE_TYPE: png
      FREQUENCY: 900  # Frequency in seconds (900 seconds :  15 minutes)
      CLEANUP_DAYS: 30  # Delete images older than 30 days
      LOG_CLEANUP_DAYS: 7  # Delete logs older than 30 days
      TIMELAPSE_ENABLED: true
      CHECKPOINT_ENABLED: true
      MAX_TIMELAPSE_SIZE: 0  # Max file size in MB (0 for unlimited)
      TIMELAPSE_FORMAT: mp4
      TIMELAPSE_SPEED: 30  # Frame rate for timelapse in fps
      MAX_IMAGE_SIZE: 0  # Max image size in KB (0 for no compression)
      LOG_LEVEL: INFO  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
      TIME_START: "00:00"  # Start time in 24-hour format
      TIME_STOP: "00:00"  # Stop time in 24-hour format