services:
  unifi-timelapser:
    build: .
    container_name: unifi-timelapser
    # image: unifi-timelapser:latest
    volumes:
      - ./src:/usr/src/app
      - ./unifi-timelapser/media:/media
      - ./unifi-timelapser/logs:/logs
      - ./config.yaml:/usr/src/app/config.yaml
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      CAMERA_RTSPS_LIST: ${CAMERA_RTSPS_LIST}
      CAMERA_NAME_LIST: ${CAMERA_NAME_LIST}
